### ISSUE TITLE
Crash if you exit the app without closing it, then try to open it up again

### ISSUE THREAD

**Issue by BIJC** [lubaochuan/RN-ToDoList#2]
If you exit the app by clicking the back button on android then attempt to access it again from the menu it crashes the app.

**Comment by lubaochuan** [comment]
This issue is fixed in [this commit](https://github.com/lubaochuan/RN-ToDoList/commit/4bdebbebbf777eb9aad0dada4f7fef5b55c865d0). 	
Firebase session persists after restart so we need to initialize SDK exactly once (the first app start after installation).
